ALTER TABLE `forbes2021` CHANGE `id` `id` INT(11) NOT NULL AUTO_INCREMENT, 
CHANGE `Rank` `rank` INT(11) NULL DEFAULT NULL, 
CHANGE `Name` `name` VARCHAR(56) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL, 
CHANGE `Country` `country` VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL, 
CHANGE `Sales` `sales` VARCHAR(8) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL, 
CHANGE `Profit` `profit` VARCHAR(9) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL, 
CHANGE `Assets` `assets` VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL, 
CHANGE `Market_Value` `market_value` VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL, 
CHANGE `Year` `year` INT(11) NULL DEFAULT NULL;